import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <body>
    <div className={styles.container}>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.header}>CRUD APPLICATION</header>
    <form action='#' className={styles.form}>
      <label className={styles.label} name="id">
        <h3 className={styles.texth3}>ID</h3>
        <input type="text" className={styles.input} id="id"></input>
      </label>
      <label className={styles.label} name="firstname">
        <h3 className={styles.texth3}>First name</h3>
        <input type="text" className={styles.input} id="firstname"></input>
      </label>
      <label className={styles.label} name="lastname">
        <h3 className={styles.texth3}>Last Name</h3>
        <input type="text" className={styles.input} id="lastname"></input>
      </label>
      <label className={styles.label} name="email">
        <h3 className={styles.texth3}>Email</h3>
        <input type="email" className={styles.input} id="email"></input>
      </label>
      <label className={styles.label} name="phone">
        <h3 className={styles.texth3}>Phone</h3>
        <input type="text" className={styles.input} id="phone"></input>
      </label>
      <label className={styles.label} name="address">
        <h3 className={styles.texth3}>address</h3>
        <textarea type="text" className={styles.textarea} id="address"></textarea>
      </label>

      <button className={styles.button}>Submit</button>
    </form>

    <div className={styles.data}>
      <h4 className={styles.texth4}>Data</h4>
      <div className={styles.cards}>

        <div className={styles.card}>
              <label className={styles.label}>ID  <span>:</span><h5 className={styles.texth5}>01</h5>
              </label>
              <label className={styles.label}>First Name  <span>:</span>
              <h5 className={styles.texth5}>Arfan</h5>
              </label>
              <label className={styles.label}>Last Name  <span>:</span>
              <h5 className={styles.texth5}>Fadillah</h5>
              </label>
              <label className={styles.label}>Email  <span>:</span>
              <h5 className={styles.texth5}>arfanfadillah99@gmail.com</h5>
              </label>
              <label className={styles.label}>Phone  <span>:</span>
              <h5 className={styles.texth5}>089662605058</h5>
              </label>
              <label className={styles.label}>Address  <span>:</span>
              <h5 className={styles.texth5}>Depok, Jawa Barat</h5>
              </label>

              <div className={styles.ud}>
                <button className={styles.udbutton}>Edit</button>
                <button className={styles.udbutton}>Delete</button>
              </div>
        </div>

        

      </div>
    </div>

    </div>
    </body>
  )
}
